# Site settings
baseurl = "https://katesteachingportfolio.com/"
languageCode = "en-us"
title = "Kate's Teaching Portfolio"
theme = "hugo-stellar-theme"

googleAnalytics = "" #put your google-analytics ID here

[params]
  [params.header]
    title = "Kaitlyn C. Duignan"
    description = 'Hello and welcome to my teaching protfolio. '
    #image = "images/logo.png"

  [[params.navigation]]
    name = "Home"
    href = "#top"

  [[params.navigation]]
    name = "Philosophy"
    href = "#teaching"

  [[params.navigation]]
    name = "Career"
    href = "#cert"

  [[params.navigation]]
    name = "Lessons"
    href = "#lessons"










  [params.intro]
    title = "About Me"
    description = """I am currently a passionate 3-K teacher working in NYC. My goal as
    an early childhood educator is to provide engaging play based activities that develop
    positive social, emotional, and academic growth for all students. I am currently certified
    in New York State in both early childhood and childhood education. Although I currently work in
    the early childhood field, I also have experience teaching in both second and fourth grade
    classrooms. My teaching experience also extends to include rural and urban communities as well
    as public and private institutions."""
    image = "/images/logo.png"









  [[params.section]]
    id = "teaching"
    title = "Philosophy"
    description = """*When you get, give. When you learn, teach.* -Maya Angelou"""

    # the picture is storead at static/images/
    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "Curriculum"
        description = ""
        icon = "fa-tasks"

      [[params.section.feature]]
        title = "Assessments"
        description = ""
        icon = "fa-pencil"

      [[params.section.feature]]
        title = "Differentiation"
        description = ""
        icon = "fa-globe"

      [[params.section.feature]]
        title = "Classroom Management"
        description = ""
        icon = "fa-users"

      [[params.section.feature]]
        title = "Collaboration and Communication"
        description = ""
        icon = "fa-commenting"

      [[params.section.feature]]
        title = "Life Long Learner"
        description = ""
        icon = "fa-mortar-board"









  [[params.section]]
    id = "cert"
    title = "Career"
    description = ""
    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "Certification"
        description = """NYS Early Childhood Education, Birth - 1st Grade; NYS  Childhood Education, 1st Grade - 6th Grade"""
        icon = "fa-certificate"

      [[params.section.feature]]
        title = "Education"
        description = """Masters of Education, University at Buffalo, 2017;
        Bachelor of Arts in English, SUNY Geneseo, 2015"""
        icon = "fa-university"

        [[params.section.feature]]
          title = "Teaching Experience"
          description = """Assistant 3-K Teacher; Long Term Substitute 4th Grade;
          Long Term Substitute Response to Intervention (RTI) Reading Teacher; Substitute Teacher Pre-K through
          4th Grade; Student Teacher 2nd Grade; Student Teacher 4th Grade"""
          icon = "fa-suitcase"

#    [params.section.statistics]
     #  enable = true
     #  [[params.section.statistic]]
     #    icon = "fa-code-fork"
     #    value = "Fourth Grade"
     #    text = "Reader's Workshop"
     #  [[params.section.statistic]]
     #    icon = "fa-folder-open-o"
     #    value = "Second Grade"
     #    text = "Human Body"
     # [[params.section.statistic]]
     #    icon = "fa-signal"
     #    value = "Second Grade"
     #    text = "Human Body"
     #  [[params.section.statistic]]
     #    icon = "fa-diamond"
     #    value = "3-K"
     #    text = "Number Study"
     #  [[params.section.statistic]]
     #     icon = "fa-diamond"
     #     value = "3-K"
     #     text = "Number Study"


    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Resume "
        buttonUrl = "generic.html"











  [[params.section]]
    id = "lessons"
    title = "Lessons"
    description = """"""

    [params.section.features]
          enable = true
    [[params.section.feature]]
      title = "Fourth Grade Reader's Workshop"
      description = """This lesson is the first in the series within a new unit.
      The unit is an author study on Patricia Polacco with a central focus on theme within
      her texts. This first lesson is a teacher lead, whole group completion of the *Patricia Polacco*
      graphic organizer which will highligh the key information about Patricia Polacco's
      writing."""
      icon = "fa-book"
    [[params.section.feature]]
      title = "Second Grade Science Lesson"
      description = """This lesson is the first within a new science unit focused on
      exoloring the human body. It serves as an introduction to the unit as well as an
      informal pre-assessment to gain a deeper understanding of the students knoweldge
      of the human body and how it works."""
      icon = "fa-flask"
    [[params.section.feature]]
      title = "3-K Number Study Lesson"
      description = """This lesson is the eighth within a number study unit and
      is centered around the theme of symmetry. Prior to this lesson, the children
      were introduced to the concept of symmetry in a hands on activity. To also incorporate
      the children's intersts, a lesson about octopi was created to provide information
      as well as circle back to the central theme."""
      icon = "fa-hashtag"

    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Fourth Grade Lesson Plan"
        buttonUrl = "generic.html"
      [[params.section.footer.action]]
        buttontext = "Second Grade Lesson Plan"
        buttonUrl = "generic.html"
      [[params.section.footer.action]]
        buttontext = "3-K Lesson Plan"
        buttonUrl = "generic.html"










  [params.footer]
    enable = true
    title = "Mrs. D's Blog"
    description = "Check out my blog for the lastest readings."

    second_title = "Contact Me"
    email = "kcduigna@gmail.com"

    [[params.footer.action]]
      href = "blog.html"
      buttontext = "Blog"

    # copyright
    [params.footer.copyright]
      enable = true
      text = "© Untitled, Design: [HTML5UP](//html5up.net)"
