# Site settings
baseurl = "https://katesteachingportfolio.com/"
languageCode = "en-us"
title = "Kate's Teaching Portfolio"
theme = "hugo-stellar-theme"

googleAnalytics = "" #put your google-analytics ID here

[params]
  [params.header]
    title = "Kaitlyn C. Duignan"
    description = 'Hello and welcome to my teaching protfolio. '
    image = "images/logo.svg"

  [[params.navigation]]
    name = "Home"
    href = "#home"

  [[params.navigation]]
    name = "Philosophy"
    href = "#teaching"

  [[params.navigation]]
    name = "Career"
    href = "#cert"

  [[params.navigation]]
    name = "Lessons"
    href = "#lessons"

  [params.intro]
    title = "About Me"
    description = """I am currently a passionate 3-K teacher working in NYC. My goal as
    an early childhood educator is to provide engaging play based activities that develop
    positive soical, emotional, and academic growith for all students. I am currently certified
    in New York State as an earch childhood and childhood educator. Although I currently work in
    the early childhood field, I also have esperience teaching in both second and fourth grade
    classrooms. My teaching experience also extends to include rural and urban communities as well
    as public and private institutions."""
    image = "/images/face.png"



  [[params.section]]
    id = "teaching"
    title = "Philosophy"
    description = """Curriculum; Assessments; Differentiated"""

    # the picture is storead at static/images/
    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "Curriculum"
        description = """Units and lessons based on state standards, approved developmental
        milestones, student interest, and creating cross-curricular connections."""
        icon = "fa-code"

      [[params.section.feature]]
        title = "Assessments"
        description = """Pre-Assessments; Summative Assessments; Formative Assessments;
        Standadized or Norm Tests"""
        icon = "fa-copy"

      [[params.section.feature]]
        title = "Differentiation"
        description = "Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat."
        icon = "fa-diamond"

      [[params.section.feature]]
        title = "Life Long Learner"
        description = """Even as a teacher I am a life long learner. Demonstrating to students to do
        the same. Expose them to opportunities to develop this love of learning"""
        icon = "fa-diamond"

      [[params.section.feature]]
        title = "Collaboration and Communication"
        description = """Principal, direcotr, co-teachers, parents/ guardians"""
        icon = "fa-code"

      [[params.section.feature]]
        title = "Classroom Management"
        description = """Positivie guidance; PBIS; Verbal and non-verabl communication"""
        icon = "fa-copy"

    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [[params.section]]
    id = "second"
    title = "Career"
    description = """Certification, Education, Teaching Experience"""
    [params.section.statistics]
      enable = true
      [[params.section.statistic]]
        icon = "fa-code-fork"
        value = "Fourth Grade"
        text = "Reader's Workshop"
        buttontext = "Lesson Plan"
        buttonUrl = "generic.html"
      [[params.section.statistic]]
        icon = "fa-folder-open-o"
        value = "Second Grade"
        text = "Insects"


#      [[params.section.statistic]]
      #   icon = "fa-signal"
      #   value = "Second Grade"
      #   text = "Human Body"
      # [[params.section.statistic]]
      #   icon = "fa-diamond"
      #   value = "3-K"
      #   text = "Density"
      # [[params.section.statistic]]
      #   icon = "fa-diamond"
      #   value = "3-K"
      #   text = "Number Study"

    [params.section.content]
      enable = true
      text = "hello world"

    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Reader's Workshop"
        buttonUrl = "generic.html"


  [[params.section]]
    id = "cta"
    title = "Lessons"
    description = """Fourth Grade Guided Reading; 3-K Lesson on Octopi"""
    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Get Started"
        buttonUrl = "generic.html"
        customClass = "special"
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [params.footer]
    enable = true
    title = "Mrs. D's Blog"
    description = "Check out my blog for the lastest readings."

    second_title = "Contact Me"
    email = "kcduigna@gmail.com"

    [[params.footer.action]]
      href = "generic.html"
      buttontext = "Blog"


    # copyright
    [params.footer.copyright]
      enable = true
      text = "© Untitled, Design: [HTML5UP](//html5up.net)"
